[package]
name = "necromanzer"
version = "0.1.0"
authors = ["Ilya Agafonov <tairesh.rus@gmail.com>"]
build = "build.rs"

#[dependencies.sdl2]
#version = "0.34"
#default-features = false
#features = ["ttf","image","mixer","unsafe_textures"]

[dependencies.tetra]
git = "https://github.com/17cupsofcoffee/tetra"
default-features = false
features = ["serde_support","texture_png","texture_jpeg","font_ttf"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
enum_dispatch = "0.3.7"
lazy_static = "1.4"

[build-dependencies]
winres = "0.1"