[package]
name = "necromanzer"
version = "0.1.0"
authors = ["Ilya Agafonov <tairesh.rus@gmail.com>"]
build = "build.rs"

[dependencies.sdl2]
version = "0.32"
default-features = false
features = ["ttf","image","mixer","unsafe_textures"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
enum_dispatch = "0.3.7"

[build-dependencies]
winres = "0.1"