name: Cargo check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev libfreetype6-dev
      - uses: actions/checkout@v1
      - uses: icepuma/rust-action@master
        with:
          args: cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test