name: tests

on:
  push:
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
    branches:
      - main
  pull_request:
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  NECROMANZER_VERSION_POSTFIX: "-test"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Install SDL2"
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev
      - name: "Install Rust toolchain"
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true
      - name: "Install required cargo"
        run: cargo install clippy-sarif sarif-fmt
      - name: "Check codestyle"
        run: cargo fmt -- --check --verbose
      - name: "Run tests"
        run: cargo test --verbose
      - name: "Run rust-clippy"
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
      - name: "Upload analysis results to GitHub"
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
