name: tests

on:
  push:
    paths:
      - '**/*.rs'
  pull_request:
    paths:
      - '**/*.rs'

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: "Install dependencies"
        run: |
          sudo apt install -y libsdl2-dev
          rustup update
      - name: "Build"
        run: |
          rustc --version
          cargo build
      - name: "Test"
        run: |
          cargo fmt -- --check
          cargo clippy -- -Dwarnings
          cargo test
