name: tests

on:
  push:
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
    branches:
      - main
  pull_request:
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  NECROMANZER_VERSION_POSTFIX: "-test"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Install SDL2"
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev
      - name: "Install Rust toolchain"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - name: "Check codestyle"
        run: cargo fmt -- --check --verbose
      - name: "Run cargo-check"
        run: cargo check --verbose
      - name: "Run tests"
        run: cargo test --verbose
      - name: "Run rust-clippy"
        run: cargo clippy -- -Dwarnings --verbose
      - uses: codecov/codecov-action@v2
